table underwriting_cockpit
	lineageTag: 665bdbc0-531e-4874-b6d0-8212a7304262

	column 'Application ID'
		dataType: string
		lineageTag: e4012845-7841-49d7-9b24-41b6851323a1
		summarizeBy: none
		sourceColumn: Application ID

		annotation SummarizationSetBy = Automatic

	column 'Applicant Name'
		dataType: string
		lineageTag: faf470f7-5977-4ea3-9451-67009d307b5a
		summarizeBy: none
		sourceColumn: Applicant Name

		annotation SummarizationSetBy = Automatic

	column 'Risk Score'
		dataType: int32
		formatString: 0
		lineageTag: 6a1cf645-c310-47f7-9b84-d42ac22cfc4c
		summarizeBy: sum
		sourceColumn: Risk Score

		annotation SummarizationSetBy = Automatic

	column 'Underwriting Decision'
		dataType: string
		lineageTag: 403934ba-c2eb-496f-bfe2-057c75a2cb04
		summarizeBy: none
		sourceColumn: Underwriting Decision

		annotation SummarizationSetBy = Automatic

	partition underwriting_cockpit = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\lukas.lehnert\Downloads\underwriting_cockpit.csv"),[Delimiter=",", Columns=4, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Application ID", type text}, {"Applicant Name", type text}, {"Risk Score", Int64.Type}, {"Underwriting Decision", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

